package com.upwind.pojo;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String detail_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.is_default
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer is_default;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.consumer_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer consumer_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.district
     *
     * @return the value of address.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.district
     *
     * @param district the value for address.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail_addr
     *
     * @return the value of address.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getDetail_addr() {
        return detail_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail_addr
     *
     * @param detail_addr the value for address.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr == null ? null : detail_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.is_default
     *
     * @return the value of address.is_default
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getIs_default() {
        return is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.is_default
     *
     * @param is_default the value for address.is_default
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setIs_default(Integer is_default) {
        this.is_default = is_default;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.consumer_id
     *
     * @return the value of address.consumer_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getConsumer_id() {
        return consumer_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.consumer_id
     *
     * @param consumer_id the value for address.consumer_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setConsumer_id(Integer consumer_id) {
        this.consumer_id = consumer_id;
    }
}