package com.upwind.pojo;

public class Consumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.gender
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.identity_num
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String identity_num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.id
     *
     * @return the value of consumer.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.id
     *
     * @param id the value for consumer.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.phone
     *
     * @return the value of consumer.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.phone
     *
     * @param phone the value for consumer.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.password
     *
     * @return the value of consumer.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.password
     *
     * @param password the value for consumer.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.name
     *
     * @return the value of consumer.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.name
     *
     * @param name the value for consumer.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.gender
     *
     * @return the value of consumer.gender
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.gender
     *
     * @param gender the value for consumer.gender
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.identity_num
     *
     * @return the value of consumer.identity_num
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getIdentity_num() {
        return identity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.identity_num
     *
     * @param identity_num the value for consumer.identity_num
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setIdentity_num(String identity_num) {
        this.identity_num = identity_num == null ? null : identity_num.trim();
    }
}