package com.upwind.pojo;

public class Courier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.job_no
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private String job_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.phone
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.password
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.name
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.gender
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.identity_num
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private String identity_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courier.outlet_id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    private Integer outlet_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.id
     *
     * @return the value of courier.id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.id
     *
     * @param id the value for courier.id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.job_no
     *
     * @return the value of courier.job_no
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public String getJob_no() {
        return job_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.job_no
     *
     * @param job_no the value for courier.job_no
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setJob_no(String job_no) {
        this.job_no = job_no == null ? null : job_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.phone
     *
     * @return the value of courier.phone
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.phone
     *
     * @param phone the value for courier.phone
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.password
     *
     * @return the value of courier.password
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.password
     *
     * @param password the value for courier.password
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.name
     *
     * @return the value of courier.name
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.name
     *
     * @param name the value for courier.name
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.gender
     *
     * @return the value of courier.gender
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.gender
     *
     * @param gender the value for courier.gender
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.identity_num
     *
     * @return the value of courier.identity_num
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public String getIdentity_num() {
        return identity_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.identity_num
     *
     * @param identity_num the value for courier.identity_num
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setIdentity_num(String identity_num) {
        this.identity_num = identity_num == null ? null : identity_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courier.outlet_id
     *
     * @return the value of courier.outlet_id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public Integer getOutlet_id() {
        return outlet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courier.outlet_id
     *
     * @param outlet_id the value for courier.outlet_id
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    public void setOutlet_id(Integer outlet_id) {
        this.outlet_id = outlet_id;
    }
}