package com.upwind.pojo;

public class Outlet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.title
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outlet.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String detail_addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.id
     *
     * @return the value of outlet.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.id
     *
     * @param id the value for outlet.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.title
     *
     * @return the value of outlet.title
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.title
     *
     * @param title the value for outlet.title
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.phone
     *
     * @return the value of outlet.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.phone
     *
     * @param phone the value for outlet.phone
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.password
     *
     * @return the value of outlet.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.password
     *
     * @param password the value for outlet.password
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.name
     *
     * @return the value of outlet.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.name
     *
     * @param name the value for outlet.name
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.province
     *
     * @return the value of outlet.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.province
     *
     * @param province the value for outlet.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.city
     *
     * @return the value of outlet.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.city
     *
     * @param city the value for outlet.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.district
     *
     * @return the value of outlet.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.district
     *
     * @param district the value for outlet.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outlet.detail_addr
     *
     * @return the value of outlet.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getDetail_addr() {
        return detail_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outlet.detail_addr
     *
     * @param detail_addr the value for outlet.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr == null ? null : detail_addr.trim();
    }
}