package com.upwind.pojo;

public class Receivewise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private String detail_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.receiver_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer receiver_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receivewise.courier_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    private Integer courier_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.id
     *
     * @return the value of receivewise.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.id
     *
     * @param id the value for receivewise.id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.province
     *
     * @return the value of receivewise.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.province
     *
     * @param province the value for receivewise.province
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.city
     *
     * @return the value of receivewise.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.city
     *
     * @param city the value for receivewise.city
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.district
     *
     * @return the value of receivewise.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.district
     *
     * @param district the value for receivewise.district
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.detail_addr
     *
     * @return the value of receivewise.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public String getDetail_addr() {
        return detail_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.detail_addr
     *
     * @param detail_addr the value for receivewise.detail_addr
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr == null ? null : detail_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.receiver_id
     *
     * @return the value of receivewise.receiver_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getReceiver_id() {
        return receiver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.receiver_id
     *
     * @param receiver_id the value for receivewise.receiver_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setReceiver_id(Integer receiver_id) {
        this.receiver_id = receiver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receivewise.courier_id
     *
     * @return the value of receivewise.courier_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public Integer getCourier_id() {
        return courier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receivewise.courier_id
     *
     * @param courier_id the value for receivewise.courier_id
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    public void setCourier_id(Integer courier_id) {
        this.courier_id = courier_id;
    }
}