package com.upwind.pojo;

public class Sendwise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private String detail_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.sender_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private Integer sender_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendwise.courier_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    private Integer courier_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.id
     *
     * @return the value of sendwise.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.id
     *
     * @param id the value for sendwise.id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.province
     *
     * @return the value of sendwise.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.province
     *
     * @param province the value for sendwise.province
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.city
     *
     * @return the value of sendwise.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.city
     *
     * @param city the value for sendwise.city
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.district
     *
     * @return the value of sendwise.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.district
     *
     * @param district the value for sendwise.district
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.detail_addr
     *
     * @return the value of sendwise.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public String getDetail_addr() {
        return detail_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.detail_addr
     *
     * @param detail_addr the value for sendwise.detail_addr
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setDetail_addr(String detail_addr) {
        this.detail_addr = detail_addr == null ? null : detail_addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.sender_id
     *
     * @return the value of sendwise.sender_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public Integer getSender_id() {
        return sender_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.sender_id
     *
     * @param sender_id the value for sendwise.sender_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setSender_id(Integer sender_id) {
        this.sender_id = sender_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendwise.courier_id
     *
     * @return the value of sendwise.courier_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public Integer getCourier_id() {
        return courier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendwise.courier_id
     *
     * @param courier_id the value for sendwise.courier_id
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    public void setCourier_id(Integer courier_id) {
        this.courier_id = courier_id;
    }
}