package com.upwind.mapper;

import com.upwind.pojo.Courier;
import com.upwind.pojo.CourierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    long countByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int deleteByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int insert(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int insertSelective(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    List<Courier> selectByExample(CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    Courier selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int updateByExampleSelective(@Param("record") Courier record, @Param("example") CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int updateByExample(@Param("record") Courier record, @Param("example") CourierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int updateByPrimaryKeySelective(Courier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courier
     *
     * @mbg.generated Sun Oct 16 16:52:45 CST 2022
     */
    int updateByPrimaryKey(Courier record);
}