package com.upwind.mapper;

import com.upwind.pojo.Express;
import com.upwind.pojo.ExpressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    long countByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int deleteByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int insert(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int insertSelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    List<Express> selectByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    Express selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int updateByExampleSelective(@Param("record") Express record, @Param("example") ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int updateByExample(@Param("record") Express record, @Param("example") ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int updateByPrimaryKeySelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Oct 29 16:34:20 CST 2022
     */
    int updateByPrimaryKey(Express record);
}