package com.upwind.mapper;

import com.upwind.pojo.Outlet;
import com.upwind.pojo.OutletExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutletMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    long countByExample(OutletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int deleteByExample(OutletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int insert(Outlet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int insertSelective(Outlet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    List<Outlet> selectByExample(OutletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    Outlet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Outlet record, @Param("example") OutletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByExample(@Param("record") Outlet record, @Param("example") OutletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByPrimaryKeySelective(Outlet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outlet
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByPrimaryKey(Outlet record);
}