package com.upwind.mapper;

import com.upwind.pojo.Sendwise;
import com.upwind.pojo.SendwiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SendwiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    long countByExample(SendwiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int deleteByExample(SendwiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int insert(Sendwise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int insertSelective(Sendwise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    List<Sendwise> selectByExample(SendwiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    Sendwise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Sendwise record, @Param("example") SendwiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByExample(@Param("record") Sendwise record, @Param("example") SendwiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByPrimaryKeySelective(Sendwise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sendwise
     *
     * @mbg.generated Thu Oct 27 17:00:07 CST 2022
     */
    int updateByPrimaryKey(Sendwise record);
}